export const GET_CATEGORY_DATA = "get_category_data"
export const GET_COMMENT_DATA = "get_comment_data"
export const GET_HOMES_DATA = "get_homes_data"
export const GET_SEARCH_DATA = "get_search_data"
export const GET_DEFALUT_DATA = "get_defalut_data"
